### ISSUE TITLE
Adapting for Ubuntu Systems?

### ISSUE THREAD

**Issue by AlexanderPlaza** [zaps166/tdesktop-hunspell#1]
Hello Zapps116,

I came across your project while looking into if telegram can be edited to have hunspell or any kind of spell checker.

I am very new into the field of github and programming. I saw in the original tread that there is a way to adapt the current client to use hunspell by importing a few things. However I am not sure how to do that exactly. Can you point me in the right direction so I can start creating a fork to include hunspell support for Ubuntu?

Thank you very much in advance.

**Comment by zaps166** [comment]
Hi, sorry for the delay, I missed this issue.

Currently this repo has obsolete packages and scripts. PKGBUILD is designed for Arch Linux. For Ubuntu you must get the hunspell patch, apply (and resolve conflicts) and compile on your own...

Still don't understand why official telegram doesn't have spellchecker...
