### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by bararchy** [zaps166/tdesktop-hunspell#2]
Hi @zaps166 , your spellcheck is awesome, but I do like updates :) is there anyway you can pull latest changes back here ? 

Thanks

**Comment by bararchy** [comment]
NM my bad, looked at package and I see you use latest and patch against it.

**Comment by zaps166** [comment]
Hi, this repo contains only PKGBUILD script and hunspell patch. Currently it is obsolete.

Still don't understand why official telegram doesn't have spellchecker...

**Comment by bararchy** [comment]
@zaps166 Not sure my self, but as my workplace is using Telegram and I'm done making my self looking a fool with typos XD I'd like to use your fork.
Hope you keep it maintained  for us :) 
Thanks for the hard work

**Comment by zaps166** [comment]
@bararchy Does it still work (the old version)? Currently I use official package, because their build system is horrible and consumes too much time for patching it and rebuilding even if somebody is doing AUR package.

**Comment by bararchy** [comment]
@zaps166 Seems it's "working" in the sense that Telegram starts and runs, but the spell-checking isn't working

**Comment by zaps166** [comment]
> (...) your spellcheck is awesome
> (...) but the spell-checking isn't working

Don't understand this 😄 

Try to install `hunspell-en` package.

**Comment by bararchy** [comment]
LOL yeha, I meant the idea is awesome I really need it.
But, currently does not seems to work, the package is installed

**Comment by zaps166** [comment]
Updated to 1.1.23, works for me, Polish and English spellchecking.

**Comment by bararchy** [comment]
@zaps166 
```
  -> Found telegram-desktop.desktop
  -> Found tg.protocol
  -> Found aur-fixes.diff
  -> Found libtgvoip-fixes.diff
==> ERROR: hunspell-telegram.diff was not found in the build directory and is not a URL.

```

**Comment by zaps166** [comment]
Oops, I forgot to push this file. Now you can try to install https://github.com/zaps166/tdesktop-hunspell/releases/download/1.1.23-hunspell/telegram-desktop-1.1.23-1-x86_64.pkg.tar.gz using pacman -U

**Comment by bararchy** [comment]
@zaps166 Thanks, it works using your release :)

**Comment by zaps166** [comment]
Added missing file :)
