### ISSUE TITLE
Make a AUR package

### ISSUE THREAD

**Issue by Gfurst** [zaps166/tdesktop-hunspell#3]
Would you consider adding this to the AUR? It could breath new life into it, and perhaps incite some maintainers.

**Comment by zaps166** [comment]
Oops, I didn't notice this issue. Github never sends me email of new issue (don't know why).

Repository is now up-to-date with telegram-desktop 1.3.10 and official ArchLinux package.

**Comment by zaps166** [comment]
PKGBUILD and other patches (except `Hunspell.cpp` and `hunspell-telegram.diff`) are copied from official package.

I don't want to update this every time. Maybe somebody else could create AUR package and use my `Hunspell.cpp` file?

**Comment by Gfurst** [comment]
Hey thanks for replying, I have to idea how to the create an AUR package, but I'm pretty sure it can be automated to fetch a source from somewhere else and apply your patch. You might need to ask for someone with more experience though. 

In any case, how would I go for building this on my own?

**Comment by zaps166** [comment]
> In any case, how would I go for building this on my own?

Clone this repository, go to new directory and run `makepkg`:
```
git clone https://github.com/zaps166/tdesktop-hunspell.git
cd tdesktop-hunspell
makepkg
```

You must install build dependencies before building, so install them (`makepkg` will display what is missing).

Also it is wise to set `MAKEFLAGS=-j12` (number after `j` is the number of CPU threads) to make build much faster e.g. by editing `/etc/makepkg.conf` before build.

**Comment by zaps166** [comment]
Telegram already supports spell checking.
